language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: jmsmyth@users.noreply.github.com
  api_key:
    secure: kX/IHyN1Ge73UmDLB8J9bVC/b/PqwgTDAkevhSP73NH2zMFLCqEXCL+iOzZQ4JuPPU3gOQMcBW68FVPTUvb2ACNhcNChP8vPoFqn18q7P2C9C6PbH2tjL3dFjHnr+lznbw9vtf6k0QvV9XdieeQDwC2AR7dm8bjh9pcnaZUmCLL5+RaA1S9HVmHYkPR9jsu60poPmnI6U3j66i9LqGvYsm2DajxJuR1R5sG3AjMwxuq00ByN8c2u9ZTjdtsAT4YSh4eom4Rdd0qT30l9QtzHqj5b2pqV3O7FAZhCmvQpWlMZWrp8xPgYPG2geCemEh/ooqZZj4z2QJISKw3AyAFcaxM+lC1NbtlNtM7CiPegYWkpP7SwCa+AF7L+8bNey6M1ZyVO0/ypwNyXxstAs4oRedoynHQxS+wL7QLWuC+xlx6/0eEvDuVh5yYpFoPJ3ltQX0No1dSWuOejn+oQc9wazUz2GX8y6NSOLv+ZxavfsHA/fEDcufqhpaM6zL+3rUeMv1XY4M3NFJtHNr6+I+CYZJz5tqOz9MVmq8B9cU7/AShQO0R0QTVkEHKArybPU0vAXIigWXuK5B2FERRLhzSbELsQarZipgVeTT6GzwNPUg6/GUsilFiadp4ESe178d009OttF9xrVqMG0C00RQZkTXR346njRi24RK0sm4yK7n4=
  on:
    tags: true
    repo: jmsmyth/browser-test-runner
