language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: jmsmyth@users.noreply.github.com
  api_key:
    secure: Zm9TWCkbg+avNA39EXLQ9wOzANEY2CrUJqrxkVl6CX88LYfwh9bM3vJIlsXOD2S/SdDkl7IOFLrOlD7++rd2GDAoNvNoGpkPD98G7J3f5ItfTOOIKuKjX+kPGSmeZsuJlKbehmdrftQ62knlxTlKFSDXhon1acFZ7x7Chk2A7biDXVSaHNjxqJZwq58gnX2Dbpr3ZzjQQ9i+guHqybPK6kTIuLM2FO+Y9V3D0wvz7BGV5sfsE39rtwHPEem3rDiJ6HD/g/yz+rSvM3rN4EekBNEbszLkN9ImQEnTpuurNPMXWfMHvtHNBnMQadRnkyn+WxfqUiPvxZvzpnCZfnkLRnbP8WsG9eSbOJflzZLDEohlNkrVsnpCoTOzR23t/Tg9tkGwekCtykEwTMDVFBCgxMzv7Ju3WL+/JmIcG9Bjo+aoGL6Q42p5/tQYVrciJF47TeCNzgsZUvlFKJFpV6f9O013HhGbdJYWRoLJkQv4j9qoXsEM8NXC3pJfyfOLVpMtydQaBDEZq0Dl8EJK7lX28kCEag0nl8Ooa+zaktyhaLek51xyLpHSHwbYxxAq1tXN+lW8Aoss4bMGwdPLFB6/ir7IL+b1qNxphjnYECUeobD0Fc3xmdx35RhlijyXIFk3sHRPZobSv5b+unwRhETPx6SamoLRKqzSLVXKjcBbV0E=
  on:
    tags: true
    repo: jmsmyth/browser-test-runner
